# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "ubuntu-server" do |us|
    us.vm.box = "ubuntu/jammy64"
    us.vm.synced_folder ".", "/vagrant", disabled: true
    #us.disksize.size = "25GB"
    us.vm.hostname = "ub-server"
    
    us.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "ubuntu22-server"
      vb.memory = "512"
      vb.cpus = "1"     
    end

    us.vm.provision "shell", path: "./scripts/0-banner-ub-server.sh"
    us.vm.provision "shell", path: "./scripts/1-script-inicial.sh"
    us.vm.provision "shell", path: "./scripts/99-script-cierre.sh"
    
  end
end
